services:
  final-mongo:
    image: mongo:6
    container_name: final-mongo
    ports:
      - "27017:27017"
    networks: [final-net]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 5s
      retries: 40
      start_period: 10s

  final-kafka:
    image: bitnami/kafka:3.6
    container_name: final-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft single-node
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://final-kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Para single node, Bitnami usa localhost en el controlador; mantenlo así:
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks: [final-net]
    healthcheck:
      # Espera a que el broker atienda en 9092
      test: ["CMD", "bash", "-lc", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 40s

  final-kafka-consumer:
    build:
      context: .
      dockerfile: app/kafka_consumer/Dockerfile
    image: final-local/kafka-consumer:latest
    env_file: .env
    environment:
      - MONGO_URI=mongodb://final-mongo:27017/lol
      - MONGO_DB=lol
      - MONGO_COLL=matches
      - KAFKA_BOOTSTRAP=final-kafka:9092
      - KAFKA_TOPIC=matches
      - GROUP_ID=final-consumer
    depends_on:
      final-kafka:
        condition: service_healthy
      final-mongo:
        condition: service_started
    command: [ "python","-m","src.ingestion.consumer" ]
    networks: [ final-net ]

  final-riot-fetcher:
    build:
      context: .
      dockerfile: app/riot_fetcher/Dockerfile
    image: final-local/riot-fetcher:latest
    env_file: .env
    environment:
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP:-final-kafka:9092}
      - TOPIC=${TOPIC:-matches}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - SUMMONER_NAME=${SUMMONER_NAME}
      - RIOT_REGION=${RIOT_REGION:-euw1}
      - RIOT_REGIONAL_ROUTE=${RIOT_REGIONAL_ROUTE:-europe}
      - POLL_INTERVAL_SECS=${POLL_INTERVAL_SECS:-20}
      - MAX_MATCHES=${MAX_MATCHES:-5}
      - PYTHONUNBUFFERED=1
    depends_on:
      final-kafka:
        condition: service_healthy
    command: [ "python","-m","src.ingestion.riot_fetcher" ]
    networks: [ final-net ]

networks:
  final-net:
    external: false
